<?php

use Illuminate\Database\Seeder;

class FornecedoresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('fornecedores')->delete();
        
        \DB::table('fornecedores')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nome' => 'Casa Santa Luzia',
            'telefone' => '(11) 3897-5000',
                'endereco' => 'al. Lorena, 1471',
                'bairro' => 'Cerqueira Cezar',
                'cidade' => 'São Paulo',
                'site' => 'http://www.santaluzia.com.br',
                'cep' => '01424-002',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            1 => 
            array (
                'id' => 2,
                'nome' => 'Empório Santa Maria',
            'telefone' => '(11) 3706-5211',
                'endereco' => 'av. Cidade Jardim, 790 ',
                'bairro' => 'Jd. Paulistano',
                'cidade' => 'São Paulo',
                'site' => 'http://www.emporiosantamaria.com.br',
                'cep' => '01454-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            2 => 
            array (
                'id' => 3,
                'nome' => 'St. Marche',
            'telefone' => '(11) 3744.5595',
                'endereco' => 'rua Comendador Adibo Ares, 275',
                'bairro' => 'Jd. Guedala',
                'cidade' => 'São Paulo',
                'site' => 'http://www.marche.com.br',
                'cep' => '05613-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            3 => 
            array (
                'id' => 4,
                'nome' => 'Korin',
            'telefone' => '(11) 5579-9363 ',
                'endereco' => 'Rua Cel. Arthur de Godoy, 246',
                'bairro' => 'Vila Mariana',
                'cidade' => 'São Paulo',
                'site' => 'http://www.korin.com.br',
                'cep' => '04018-050',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            4 => 
            array (
                'id' => 5,
                'nome' => 'Éthos',
            'telefone' => '(11) 3832-6362',
                'endereco' => 'Av. Dr. Gastão Vidigal, 1.946 - Ceagesp - Pavilhão AMB - box 19/20',
                'bairro' => 'Vila Leopoldina',
                'cidade' => 'São Paulo',
                'site' => 'http://www.ethos-agro.com.br',
                'cep' => '05314-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            5 => 
            array (
                'id' => 6,
                'nome' => 'Horta em Casa',
            'telefone' => '(11) 4409-1791',
                'endereco' => 'Diversos Supermercados',
                'bairro' => '',
                'cidade' => '',
                'site' => 'http://www.hortaemcasa.com.br',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            6 => 
            array (
                'id' => 7,
                'nome' => 'Organic Delivery',
            'telefone' => '(11) 4169-4457',
                'endereco' => 'Internet',
                'bairro' => '',
                'cidade' => '',
                'site' => 'http://www.organicdelivery.com.br',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            7 => 
            array (
                'id' => 8,
                'nome' => 'Caminhos da Roça',
            'telefone' => '(11) 3733-6727',
                'endereco' => 'Internet',
                'bairro' => '',
                'cidade' => '',
                'site' => 'http://www.caminhosdaroca.com.br',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            8 => 
            array (
                'id' => 9,
                'nome' => 'Pão de Açúcar',
            'telefone' => '(11) 3055-6767',
                'endereco' => 'Diversos Supermercados',
                'bairro' => 'Vários',
                'cidade' => 'São Paulo',
                'site' => 'https://www.paodeacucar.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            9 => 
            array (
                'id' => 10,
                'nome' => 'Caseus',
            'telefone' => '(11) 3661-6900 e (11) 3663-2570',
                'endereco' => 'Rua Alagoas, 475',
                'bairro' => 'Higienópolis',
                'cidade' => 'São Paulo',
                'site' => 'http://www.caseus.com.br',
                'cep' => '01242-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            10 => 
            array (
                'id' => 11,
                'nome' => 'Vital Gourmet Importação e Exportação Ltda.',
            'telefone' => '(11) 2693-0112 e (11) 7859-3089',
                'endereco' => 'Rua da Mooca, 1736 sl. 44',
                'bairro' => 'Mooca',
                'cidade' => 'São Paulo',
                'site' => 'http://vitalgourmet.com.br',
                'cep' => '03104-002',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            11 => 
            array (
                'id' => 12,
                'nome' => 'Petrossian',
            'telefone' => '(11) 3552-7200',
                'endereco' => 'Av. Magalhães de Castro, 12000, piso térreo, Shopping Cidade Jardim',
                'bairro' => 'Cidade Jardim',
                'cidade' => 'São Paulo',
                'site' => 'http://www.petrossianbr.com.br',
                'cep' => '05502-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            12 => 
            array (
                'id' => 13,
                'nome' => 'Empório Chiappetta',
            'telefone' => '(11) 4257-2107',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo - rua G / box 8, 12 e 14',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.emporiochiappetta.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            13 => 
            array (
                'id' => 14,
                'nome' => 'Shiitake Champ Gourmet',
            'telefone' => '(24) 2258-2167',
                'endereco' => 'Antiga Rio Bahia -Km 09 S/n',
                'bairro' => 'Bemposta',
                'cidade' => 'Três Rios',
                'site' => '',
                'cep' => '25840-000',
                'estado' => 'Rio de Janeiro',
                'pais' => 'Brasil',
            ),
            14 => 
            array (
                'id' => 16,
                'nome' => 'Comércio de Carnes Mercado Central',
            'telefone' => '(11) 3228-9316',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo - rua C / box 27',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            15 => 
            array (
                'id' => 17,
                'nome' => 'Rei do Camarão',
            'telefone' => '(11) 3312-0074',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo - rua B / box 30',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            16 => 
            array (
                'id' => 18,
                'nome' => 'Distribuidora de Carnes Cantareira',
            'telefone' => '(11) 3228-4349',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo - rua D / box 33',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            17 => 
            array (
                'id' => 19,
                'nome' => 'Laticínios São Miguel',
            'telefone' => '(11) 3326-1468 e 3328-3099',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo - rua D / box 2 e rua F / box 1',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.queijosroni.com',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            18 => 
            array (
                'id' => 20,
                'nome' => 'Casa Flora',
            'telefone' => '(11) 2842-5199 / (11) 3327-5199',
                'endereco' => 'Rua Santa Rosa, 207',
                'bairro' => 'Brás',
                'cidade' => 'São Paulo',
                'site' => 'http://www.casaflora.com.br',
                'cep' => '03007-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            19 => 
            array (
                'id' => 21,
                'nome' => 'Coopes',
                'telefone' => '',
                'endereco' => '',
                'bairro' => '',
                'cidade' => 'Piemonte da Diamantina',
                'site' => 'http://www.coopes.org.br/',
                'cep' => '',
                'estado' => 'Bahia',
                'pais' => 'Brasil',
            ),
            20 => 
            array (
                'id' => 22,
                'nome' => 'Oficina do Gosto',
            'telefone' => '(+351) 219442083',
                'endereco' => 'Rotunda Nuno Rodrigues dos Santos, Centro Comercial da Portela, loja 33 1º andar',
                'bairro' => '',
                'cidade' => 'Portela',
                'site' => 'http://oficinadogosto.com',
                'cep' => '',
                'estado' => '',
                'pais' => 'Portugal',
            ),
            21 => 
            array (
                'id' => 23,
                'nome' => 'Schehrasade',
            'telefone' => '(11) 3667-0786',
                'endereco' => 'Rua Baronesa de Itú, 340',
                'bairro' => 'Higienópolis',
                'cidade' => 'São Paulo',
                'site' => 'http://www.schehrasade.com.br',
                'cep' => '01231-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            22 => 
            array (
                'id' => 24,
                'nome' => 'Casa Líbano',
            'telefone' => '(11) 3313-0289 / (11) 3227-6116',
                'endereco' => 'Rua Barão de Ladário, 831',
                'bairro' => 'Pari',
                'cidade' => 'São Paulo',
                'site' => 'http://www.casalibano.com.br',
                'cep' => '03010-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            23 => 
            array (
                'id' => 25,
                'nome' => 'Empório Akkar',
            'telefone' => '(11) 3228-7188',
                'endereco' => 'Rua Comendador Afonso Kherlakian, 165',
                'bairro' => 'Sé',
                'cidade' => 'São Paulo',
                'site' => 'http://www.emporioakkar.com.br',
                'cep' => '01023-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            24 => 
            array (
                'id' => 26,
                'nome' => 'Empório São Jorge',
            'telefone' => '(11) 3889-8449',
                'endereco' => 'Rua Des. Eliseu Guilherme, 322',
                'bairro' => 'Paraíso',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '04004-030',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            25 => 
            array (
                'id' => 27,
                'nome' => 'Maxifour',
            'telefone' => '(11) 2799-0000',
                'endereco' => 'Rua Julio Ribeiro 66',
                'bairro' => 'Brás',
                'cidade' => 'São Paulo',
                'site' => 'http://www.maxifour.com.br',
                'cep' => '03010-030',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            26 => 
            array (
                'id' => 28,
                'nome' => 'Saddi Center',
            'telefone' => '(11) 3885-7755',
                'endereco' => 'Rua Guarará, 76',
                'bairro' => 'Jardim Paulista',
                'cidade' => 'São Paulo',
                'site' => 'http://saddicenter.com.br',
                'cep' => '01425-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            27 => 
            array (
                'id' => 29,
                'nome' => 'Açougue Pacaembu',
            'telefone' => '(11) 3865-7780',
                'endereco' => 'Rua Cardoso de Almeida, 1547',
                'bairro' => 'Perdizes',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05013-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            28 => 
            array (
                'id' => 30,
                'nome' => 'Intermezzo Gourmet',
            'telefone' => '(11) 3796-6737',
                'endereco' => 'Rua Olímpio Portugal, 148',
                'bairro' => 'Mooca',
                'cidade' => 'São Paulo',
                'site' => 'http://intermezzogourmet.com.br',
                'cep' => '03112-010',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            29 => 
            array (
                'id' => 31,
                'nome' => 'Casa de Carnes Perdizes',
            'telefone' => '(11) 3864-6340 / 3672-7691',
                'endereco' => 'Rua Piracuama, 454',
                'bairro' => 'Perdizes',
                'cidade' => 'São Paulo',
                'site' => 'http://www.carnesperdizes.com.br',
                'cep' => '05017-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            30 => 
            array (
                'id' => 32,
                'nome' => 'Wessel',
            'telefone' => '(11) 3032-3310 / 3081-8041',
                'endereco' => 'Av. Brigadeiro Faria Lima, 2.383',
                'bairro' => 'Jardim Paulistano',
                'cidade' => 'São Paulo',
                'site' => 'http://www.wessel.com.br',
                'cep' => '01452-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            31 => 
            array (
                'id' => 33,
            'nome' => 'Templo da Carne (Bassi)',
            'telefone' => '(11) 3288-7045 / 3251-1488',
                'endereco' => 'Rua Treze de Maio, 668',
                'bairro' => 'Bela Vista',
                'cidade' => 'São Paulo',
                'site' => 'http://www.templodacarne.com.br',
                'cep' => '01327-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            32 => 
            array (
                'id' => 34,
                'nome' => 'Família Orgânica',
            'telefone' => '(19) 9714-5507 / 9664-0422',
                'endereco' => '',
                'bairro' => '',
                'cidade' => 'São Paulo',
                'site' => 'http://www.familiaorganica.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            33 => 
            array (
                'id' => 35,
                'nome' => 'Multi-Nox',
            'telefone' => '(11) 3322-3100',
                'endereco' => 'Rua Paula Souza, 113 / 115',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01027-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            34 => 
            array (
                'id' => 36,
                'nome' => 'Central Equipamentos',
            'telefone' => '(11) 3325-0301',
                'endereco' => 'Rua Paula Souza, 198',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01027-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            35 => 
            array (
                'id' => 37,
                'nome' => 'Banri',
            'telefone' => '(11) 3208-7232',
                'endereco' => 'Rua Galvão Bueno, 160',
                'bairro' => 'Liberdade',
                'cidade' => 'São Paulo',
                'site' => 'http://www.banri.com.br',
                'cep' => '01506-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            36 => 
            array (
                'id' => 38,
                'nome' => 'Casa Bueno',
            'telefone' => '(11) 3277-8901',
                'endereco' => 'Rua Galvão Bueno, 48',
                'bairro' => 'Liberdade',
                'cidade' => 'São Paulo',
                'site' => 'http://www.casabueno.com.br',
                'cep' => '01506-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            37 => 
            array (
                'id' => 39,
                'nome' => 'Kaisen',
            'telefone' => '(11) 3341-6571',
                'endereco' => 'Rua Galvão Bueno, 270',
                'bairro' => 'Liberdade',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01506-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            38 => 
            array (
                'id' => 40,
                'nome' => 'Marukai',
            'telefone' => '(11) 3207-8202 / (11) 3341-3350',
                'endereco' => 'Rua Galvão Bueno, 34',
                'bairro' => 'Liberdade',
                'cidade' => 'São Paulo',
                'site' => 'http://www.marukai.com.br',
                'cep' => '01506-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            39 => 
            array (
                'id' => 41,
                'nome' => 'Mercearia Oriental',
            'telefone' => '(11) 3209 8830',
                'endereco' => 'Rua dos Estudantes, 38',
                'bairro' => 'Liberdade',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01505-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            40 => 
            array (
                'id' => 42,
                'nome' => 'Tajimaya',
            'telefone' => '(11) 32773812',
                'endereco' => 'Rua Dos Estudantes 48',
                'bairro' => 'Liberdade',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01505-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            41 => 
            array (
                'id' => 43,
                'nome' => 'Varanda',
            'telefone' => '(11) 3035-5857',
                'endereco' => 'Ponte Cidade Jardim',
                'bairro' => 'Cidade Jardim',
                'cidade' => 'São Paulo',
                'site' => 'http://www.varanda.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            42 => 
            array (
                'id' => 44,
                'nome' => 'Tabutins',
            'telefone' => '(54) 3054-5540 / (51) 4042-2132',
                'endereco' => '',
                'bairro' => '',
                'cidade' => '',
                'site' => 'http://www.tabutinssementes.com.br',
                'cep' => '',
                'estado' => 'Rio Grande do Sul',
                'pais' => 'Brasil',
            ),
            43 => 
            array (
                'id' => 45,
                'nome' => 'Bacalhau Dias',
            'telefone' => '(11) 3294-3200',
                'endereco' => 'Rua Dr. Neto de Araújo, 320 # 709',
                'bairro' => 'Vila Mariana',
                'cidade' => 'São Paulo',
                'site' => 'http://www.bacalhaudias.com.br',
                'cep' => '04111-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            44 => 
            array (
                'id' => 46,
                'nome' => 'Chez Pierre',
            'telefone' => '(11) 4409-3022 / (11) 8326-9820 / (11) 9614-1818',
                'endereco' => '',
                'bairro' => '',
                'cidade' => 'Itu',
                'site' => '',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            45 => 
            array (
                'id' => 47,
                'nome' => 'Porco Feliz',
            'telefone' => '(11) 3315-0180',
                'endereco' => 'Rua da Cantareira, 306 - rua E, box 26',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-000',
                'estado' => '',
                'pais' => '',
            ),
            46 => 
            array (
                'id' => 48,
                'nome' => 'Sabor de Fazenda',
            'telefone' => '(11) 2631-4915 / (11) 2955-9400',
                'endereco' => 'Av. Nadir Dias de Figueiredo, 395',
                'bairro' => 'Vila Maria',
                'cidade' => 'São Paulo',
                'site' => 'http://www.sabordefazenda.com.br',
                'cep' => '02110-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            47 => 
            array (
                'id' => 49,
                'nome' => 'Laticínio Gioa',
            'telefone' => '(11) 4412-8940 / 4411-0088',
                'endereco' => 'Av. Industrial Walter Kloth, 1061',
                'bairro' => 'Jardim Imperial',
                'cidade' => 'Atibaia',
                'site' => 'http://laticiniosgioia.com.br',
                'cep' => '12951-200',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            48 => 
            array (
                'id' => 50,
                'nome' => 'Aurora Fine Brands',
            'telefone' => '(11) 3623-2280',
                'endereco' => 'Rua Gomes de Carvalho, 1329 - 7º andar ',
                'bairro' => 'Vila Olímpia',
                'cidade' => 'São Paulo',
                'site' => 'http://www.aurora.com.br',
                'cep' => '04547-005',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            49 => 
            array (
                'id' => 51,
                'nome' => 'Tosello',
            'telefone' => '(19) 3832.5505',
                'endereco' => 'Rua Rialma, 120',
                'bairro' => 'Jardim Dall’Orto',
                'cidade' => 'Sumaré',
                'site' => 'http://www.tosello.com.br',
                'cep' => '13178-051',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            50 => 
            array (
                'id' => 52,
                'nome' => 'Pimenta do Jamal',
            'telefone' => '(11) 3637-0229 / (11) 9996-7726 ',
                'endereco' => 'Rua da Consolação, 2710 - CJ 33',
                'bairro' => 'Jardins',
                'cidade' => 'São Paulo',
                'site' => 'http://www.pimentadojamal.com.br',
                'cep' => '01416-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            51 => 
            array (
                'id' => 53,
                'nome' => 'Araruta do Brasil - Pedro Augusto Borges Coni',
                'telefone' => '',
                'endereco' => '',
                'bairro' => '',
                'cidade' => 'Recôncavo Baiano',
                'site' => 'contatoararuta@hotmail.com',
                'cep' => '',
                'estado' => 'Bahia',
                'pais' => 'Brasil',
            ),
            52 => 
            array (
                'id' => 54,
                'nome' => 'Adalberto e Márcia',
            'telefone' => '(11) 3812-0553',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado Municipal de Pinheiros, Boxe 4',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            53 => 
            array (
                'id' => 55,
                'nome' => 'Agrivert',
            'telefone' => '(19) 3869-3017 / (19) 3849-7281 / (19) 3849-7307 / (19) 3849-7281  ',
                'endereco' => 'Est Velha Para Itatiba, s/n km 9',
                'bairro' => '',
                'cidade' => 'Valinhos',
                'site' => 'http://www.agrivert.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            54 => 
            array (
                'id' => 56,
                'nome' => 'Carneiro & Cia',
            'telefone' => '(11) 3062-5500',
                'endereco' => 'Rua Barão de Capanema, 541',
                'bairro' => 'Jardim Paulista',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01411-011',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            55 => 
            array (
                'id' => 57,
                'nome' => 'Cogumelos Online',
            'telefone' => '(11) 4799-7042',
                'endereco' => 'Av. Narciso Yague Guimarães, 1250',
                'bairro' => 'Socorro',
                'cidade' => 'Mogi das Cruzes',
                'site' => 'http://www.cogumelosonline.com.br',
                'cep' => '08780-200',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            56 => 
            array (
                'id' => 58,
                'nome' => 'Hortifruti Natural da Terra',
            'telefone' => '(11) 3824-0582',
                'endereco' => 'Rua Rosa e Silva 163-177',
                'bairro' => 'Santa Cecília',
                'cidade' => 'São Paulo',
                'site' => 'http://www.naturaldaterra.com.br',
                'cep' => '01230-020',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            57 => 
            array (
                'id' => 59,
                'nome' => 'Agro Comercial Vizinho',
            'telefone' => '(11) 3311-6495',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 15',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            58 => 
            array (
                'id' => 60,
                'nome' => 'All Food',
            'telefone' => '(11) 2799-0422',
                'endereco' => 'Rua Javari, 219',
                'bairro' => 'Mooca',
                'cidade' => 'São Paulo',
                'site' => 'http://www.allfood.com.br',
                'cep' => '03112-100',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            59 => 
            array (
                'id' => 61,
                'nome' => 'Casa de Carnes RJ Ltda',
            'telefone' => '(11) 3813-9631',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado de Pinheiros, Box 66/67',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            60 => 
            array (
                'id' => 62,
                'nome' => 'Casa de Carnes GMS Ltda.',
            'telefone' => '(11) 3032-3629 / (11) 3815-9060',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado de Pinheiros, Box 57/58',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            61 => 
            array (
                'id' => 63,
                'nome' => 'Distribuidora de Pescados N. Sra. de Fátima',
            'telefone' => '(11) 3032-1221 / (11) 3032-0313',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado de Pinheiros, Boxes 68 a 70',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => 'www.nsrfatima.com.br',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            62 => 
            array (
                'id' => 64,
                'nome' => 'A Senhora das Especiarias',
            'telefone' => '(35) 3654-1253 / (35) 3654-1310',
                'endereco' => 'Estrada Paraisópolis-Gonçalves, km 6',
                'bairro' => '',
                'cidade' => 'Gonçalves',
                'site' => 'http://www.asenhoradasespeciarias.com.br',
                'cep' => '37680-000',
                'estado' => 'Minas Gerais',
                'pais' => 'Brasil',
            ),
            63 => 
            array (
                'id' => 65,
                'nome' => 'All Kosher',
            'telefone' => '(11) 3825-1131',
                'endereco' => 'Al. Barros, 391 loja 12',
                'bairro' => 'Santa Cecília',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01232-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            64 => 
            array (
                'id' => 66,
                'nome' => 'Aves e Ovos',
            'telefone' => '(11) 3815-8445',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado de Pinheiros, Box 74/75',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            65 => 
            array (
                'id' => 67,
                'nome' => 'Berna',
            'telefone' => '(11) 5044-3477',
                'endereco' => 'Rua Atílio Biscuola, 999',
                'bairro' => '',
                'cidade' => 'Louveira',
                'site' => 'http://www.berna.com.br',
                'cep' => '13290-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            66 => 
            array (
                'id' => 68,
                'nome' => 'Brasserie Victória',
            'telefone' => '(11) 3845-8897',
                'endereco' => 'Av. Juscelino Kubitschek, 545',
                'bairro' => 'Itaim Bibi',
                'cidade' => 'São Paulo',
                'site' => 'www.brasserievictoria.com.br',
                'cep' => '04543-010',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            67 => 
            array (
                'id' => 69,
                'nome' => 'Capricoop - Cooperativa SP-MG',
            'telefone' => '(11) 3266-5965',
                'endereco' => 'Rua Rui Barbosa, 95 sala nº 41',
                'bairro' => 'Bixiga',
                'cidade' => 'São Paulo',
                'site' => 'http://www.capricoop.com.br',
                'cep' => '01326-010',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            68 => 
            array (
                'id' => 70,
                'nome' => 'Carimbó',
            'telefone' => '(11) 3255-7555',
                'endereco' => 'Rua Bela Cintra, 483',
                'bairro' => 'Consolação',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01415-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            69 => 
            array (
                'id' => 71,
                'nome' => 'Casa das Mandiocas',
            'telefone' => '(11) 3326-1295',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 12',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            70 => 
            array (
                'id' => 72,
                'nome' => 'Banca do Santo',
            'telefone' => '(11) 3326-5428',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 50',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            71 => 
            array (
                'id' => 73,
                'nome' => 'Banca da Irene',
            'telefone' => '(11) 3326-1209',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 112 / 113',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            72 => 
            array (
                'id' => 74,
                'nome' => 'Banca da Batata',
            'telefone' => '(11) 6952-9348',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 74',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            73 => 
            array (
                'id' => 75,
                'nome' => 'Bacana Comércio de Frutas',
            'telefone' => '(11) 3316-1178',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 55',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            74 => 
            array (
                'id' => 76,
                'nome' => 'Box do "Seu" Milton',
            'telefone' => '(11) 3311-0438',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 4',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            75 => 
            array (
                'id' => 77,
                'nome' => 'Comércio de Frutas Netti Ltda',
            'telefone' => '(11) 3227-7172',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 29',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            76 => 
            array (
                'id' => 78,
                'nome' => 'KL Temperos',
            'telefone' => '(11) 3311-6226 / (11) 3311-6226 ',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 5',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadokinjo.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            77 => 
            array (
                'id' => 79,
                'nome' => 'Horti-Frutas 29 Sr. Odair',
            'telefone' => '(11) 3813-9642 / (11) 3813-3194 / (11) 3814-8480',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado de Pinheiros, Box 29',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            78 => 
            array (
                'id' => 80,
                'nome' => 'Casa Irmãos Borges',
            'telefone' => '(11) 3227-7048',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 3',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            79 => 
            array (
                'id' => 81,
                'nome' => 'Cellar',
            'telefone' => '(011) 5531.2419',
                'endereco' => '',
                'bairro' => '',
                'cidade' => '',
                'site' => 'http://www.cellar-af.com.br',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            80 => 
            array (
                'id' => 82,
                'nome' => 'Cereais Minúcia',
            'telefone' => '(11) 3031-6800',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado de Pinheiros, Box 1',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            81 => 
            array (
                'id' => 83,
                'nome' => 'CFA Paulielo',
            'telefone' => '(18) 3622-3883',
                'endereco' => 'Alameda Lorena, 1471 - Casa Santa Luzia',
                'bairro' => 'Jardim Paulista',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01424-002',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            82 => 
            array (
                'id' => 84,
                'nome' => 'Chitão Comercial',
            'telefone' => '(11) 2692-3044 / (11) 2692-8925',
                'endereco' => 'Rua Joaquim Nabuco, 238',
                'bairro' => 'Brás',
                'cidade' => 'São Paulo',
                'site' => 'http://www.produtosnordestinos.com.br',
                'cep' => '03050-020',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            83 => 
            array (
                'id' => 85,
                'nome' => 'Coelho Real',
            'telefone' => '(11) 3081-9317',
                'endereco' => 'Rua Capitão Francisco Padilha, 31',
                'bairro' => 'Jardim Europa',
                'cidade' => 'São Paulo',
                'site' => 'http://www.coelhoreal.com.br',
                'cep' => '01448-070',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            84 => 
            array (
                'id' => 86,
                'nome' => 'Lagostão Comércio e Importação de Pescados Ltda.',
            'telefone' => '(11) 3719-0186',
                'endereco' => 'Av. Rio Pequeno, 179',
                'bairro' => 'Rio Pequeno',
                'cidade' => 'São Paulo',
                'site' => 'www.lagostao.com.br',
                'cep' => '05379-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            85 => 
            array (
                'id' => 87,
                'nome' => 'Comercial de Alimentos Vida',
            'telefone' => '(11) 6618-2015 / (11) 2692-1806',
                'endereco' => 'Rua Paulo Afonso, 71',
                'bairro' => 'Brás',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '03050-030',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            86 => 
            array (
                'id' => 88,
                'nome' => 'Comércio de Miudos Luigi',
            'telefone' => '(11) 3228-1809',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Boxe 28',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            87 => 
            array (
                'id' => 89,
                'nome' => 'Frigorífico Pacífico',
            'telefone' => '(11) 3831-6000 / (11) 3831 6942',
                'endereco' => 'Rua Dr. Seidel, 300',
                'bairro' => 'Vila Leopoldina',
                'cidade' => 'São Paulo',
                'site' => 'http://www.frigorificopacifico.com.br',
                'cep' => '05315-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            88 => 
            array (
                'id' => 91,
                'nome' => 'Companhia das Ervas',
            'telefone' => '(11) 4014-7521 / (19) 3869-4101',
                'endereco' => 'Rua Felizardo Assis, 260',
                'bairro' => '',
                'cidade' => 'Morungaba',
                'site' => 'www.ciadaservas.com.br',
                'cep' => '13260-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            89 => 
            array (
                'id' => 92,
                'nome' => 'Damm',
                'telefone' => '0800 55-4412',
                'endereco' => '',
                'bairro' => '',
                'cidade' => '',
                'site' => 'www.damm.com.br',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            90 => 
            array (
                'id' => 94,
                'nome' => 'Empório Silvestre',
            'telefone' => '(11) 3082-5388 / (11) 3081-6910',
                'endereco' => 'Rua Oscar Freire, 1.607',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => 'http://emporio.tripod.com/emporio.html',
                'cep' => '05409-010',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            91 => 
            array (
                'id' => 95,
                'nome' => 'Alcachofra da Silvana',
            'telefone' => '(11) 3088-7093',
                'endereco' => 'Rua Padre João Manuel, 1089',
                'bairro' => 'Jardins',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01411-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            92 => 
            array (
                'id' => 96,
                'nome' => 'O & G Mercearia',
            'telefone' => '(11) 3313-8003 ',
                'endereco' => 'Rua Três Rios, 245',
                'bairro' => 'Bom Retiro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01123-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            93 => 
            array (
                'id' => 97,
                'nome' => 'Cooperostra',
            'telefone' => '(13) 3851-8339',
                'endereco' => 'Rua Pref. Herculado de Oliveira Rosa, 6',
                'bairro' => '',
                'cidade' => 'Cananéia',
                'site' => '',
                'cep' => '11990-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            94 => 
            array (
                'id' => 98,
                'nome' => 'Adega de Saquê',
            'telefone' => '(11) 3209-3332 / (11) 3207-2330',
                'endereco' => 'Rua Galvão Bueno, 387',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01506-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            95 => 
            array (
                'id' => 99,
                'nome' => 'Talchá',
            'telefone' => '(11) 3823-3744',
                'endereco' => 'Avenida Higienópolis, 618 - Shopping Pátio Higienópolis',
                'bairro' => 'Higienópolis',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01238-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            96 => 
            array (
                'id' => 101,
                'nome' => 'Natural com Arte - Chácara de Orgânicos',
            'telefone' => '(11) 5084-9697',
                'endereco' => 'Rua Rodrigo Vieira, 412',
                'bairro' => 'Chácara Klabin',
                'cidade' => 'Embú',
                'site' => '',
                'cep' => '04115-060',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            97 => 
            array (
                'id' => 102,
                'nome' => 'Cerrado Carnes de Caça',
            'telefone' => '(11) 4254-2004',
                'endereco' => '',
                'bairro' => '',
                'cidade' => '',
                'site' => 'http://www.cerradocarnes.com.br',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            98 => 
            array (
                'id' => 103,
                'nome' => 'La Pescatina',
                'telefone' => '',
                'endereco' => 'M. Cassab Importadora',
                'bairro' => '',
                'cidade' => '',
                'site' => '',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            99 => 
            array (
                'id' => 104,
                'nome' => 'Mais Sabor',
            'telefone' => '(11) 3031-1631 / (11) 3032-9692 / (11) 9550-5966',
                'endereco' => 'Rua Pedro Cristi, 31-71 - Mercado de Pinheiros, Boxe 76',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            100 => 
            array (
                'id' => 105,
                'nome' => 'Empório Guareí',
            'telefone' => '(11) 3819-4717',
                'endereco' => 'Rua Pedro Cristi, 31-71 - Mercado de Pinheiros, Boxes 09/10',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            101 => 
            array (
                'id' => 106,
                'nome' => 'Empório Syrio',
            'telefone' => '(11) 3228-3640',
                'endereco' => 'Rua Comendador Abdo Schahin, 136',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.emporiosyrio.com.br',
                'cep' => '01023-050',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            102 => 
            array (
                'id' => 107,
                'nome' => 'Emporium Santa Madalena',
            'telefone' => '(11) 3815-2323 / (11) 3031-3973',
                'endereco' => 'Rua Fradique Coutinho, 914 a 916',
                'bairro' => 'Vila Madalena',
                'cidade' => 'São Paulo',
                'site' => 'http://www.creazione.com.br/site/internet/sites/santa_madalena/frame.html',
                'cep' => '05416-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            103 => 
            array (
                'id' => 108,
                'nome' => 'Emporium São Paulo',
            'telefone' => '(11) 3704-3899',
                'endereco' => 'Rua Pedroso Alvarenga, 803',
                'bairro' => 'Vila Nova Conceição',
                'cidade' => 'São Paulo',
                'site' => 'http://www.emporiumsaopaulo.com.br',
                'cep' => '04531-011',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            104 => 
            array (
                'id' => 109,
                'nome' => 'Ervas Finas',
            'telefone' => '(11) 4039-1054',
                'endereco' => 'Casa Santa Luzia, Pão de Açúcar',
                'bairro' => '',
                'cidade' => 'Campo Limpo Paulista',
                'site' => 'http://ervasfinasnet.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            105 => 
            array (
                'id' => 110,
                'nome' => 'Estufas J.R.O.',
            'telefone' => '(15) 9701-9308',
                'endereco' => '',
                'bairro' => '',
                'cidade' => 'Cerquilho',
                'site' => '',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            106 => 
            array (
                'id' => 112,
                'nome' => 'Fazenda Ituaú',
            'telefone' => '(11) 4027-9018 / (11) 4027-9045',
            'endereco' => '(Estrada Velha Km 7) Santa Luzia, Santa Maria, Pão de Açúcar',
                'bairro' => '',
                'cidade' => 'Salto / Capivari',
                'site' => 'http://www.fazendaituau.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            107 => 
            array (
                'id' => 113,
                'nome' => 'Fazenda Santa Isabel',
            'telefone' => '(11) 3168-2474',
            'endereco' => '(Estrada de Ivoturucaia s/n) Santa Luzia e Pão de Açúcar Lojas Top',
                'bairro' => '',
                'cidade' => 'Jundiaí',
                'site' => 'http://www.fazenda-sta-isabel.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            108 => 
            array (
                'id' => 114,
                'nome' => 'Fazenda Santo Onofre',
            'telefone' => '(11) 4534-9700 / (11) 9312-0934',
                'endereco' => 'Santa Luzia, Santa Maria, Pão de Açúcar Lojas Top',
                'bairro' => '',
                'cidade' => 'São Paulo',
                'site' => 'http://fazendasantoonofre.com.br',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            109 => 
            array (
                'id' => 115,
                'nome' => 'Freddi Carnes',
            'telefone' => '(11) 5053-5200',
                'endereco' => 'Av. Lavandisca, 665',
                'bairro' => 'Moema',
                'cidade' => 'São Paulo',
                'site' => 'http://www.freddicarnes.com.br/',
                'cep' => '04515-011',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            110 => 
            array (
                'id' => 116,
                'nome' => 'Frigor Cinque',
            'telefone' => '(011) 4148 1956',
                'endereco' => 'Rua Martiniano Lemos Leite, 30 - Condomínio Trade Hil',
                'bairro' => 'Vila Jovina',
                'cidade' => 'Cotia',
                'site' => 'http://frigorcinque.com.br/index.html',
                'cep' => '06705-110',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            111 => 
            array (
                'id' => 117,
                'nome' => 'Ganesh',
            'telefone' => '(11) 5181-4748',
                'endereco' => 'Avenida Roque Petroni Júnior, 1089 - Shopping Morumbi',
                'bairro' => 'Morumbi',
                'cidade' => 'São Paulo',
                'site' => 'http://www.ganesh.com.br',
                'cep' => '04707-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            112 => 
            array (
                'id' => 118,
            'nome' => 'Granja Santa Rita (pode entregar em casa - qtd.)',
            'telefone' => '(13) 3846-6143',
                'endereco' => 'Avicola Rolim, Santa Luzia, Santa Maria, Mambo, Varanda',
                'bairro' => '',
                'cidade' => 'Santa Rita do Ribeira',
                'site' => '',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            113 => 
            array (
                'id' => 119,
                'nome' => 'Avícola Rolim',
            'telefone' => '(11) 3229-6894 / (11) 3229-6171',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Box 21',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://avicolarolim.com.br/default.asp',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            114 => 
            array (
                'id' => 120,
                'nome' => 'Hortifruti Kote',
            'telefone' => '(11) 5548-1405',
                'endereco' => 'Rua Padre José de Anchieta, 953',
                'bairro' => 'Santo Amaro',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '04742-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            115 => 
            array (
                'id' => 121,
                'nome' => 'Il Pianeta',
            'telefone' => '(11) 3079-3800',
                'endereco' => 'Rua Pedroso Alvarenga, 1.203',
                'bairro' => 'Itaim Bibi',
                'cidade' => 'São Paulo',
                'site' => 'http://www.ilpianeta.com.br',
                'cep' => '04531-012',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            116 => 
            array (
                'id' => 122,
                'nome' => 'Isetan',
            'telefone' => '(11) 3208-3980',
                'endereco' => 'R. dos Estudantes, 48',
                'bairro' => 'Liberdade',
                'cidade' => 'São Paulo',
                'site' => 'http://www.restaurantesjaponeses.com.br',
                'cep' => '01505-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            117 => 
            array (
                'id' => 123,
                'nome' => 'Javalix',
            'telefone' => '(11) 3865.1474 / (11) 3611-7784',
            'endereco' => 'R. Ermelinda Americano, 123 (Santa Luzia, Santa Maria, Pão de Açúcar Lojas Top, Varanda)',
                'bairro' => 'Perdizes',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05007-050',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            118 => 
            array (
                'id' => 125,
                'nome' => 'La Bufalina',
            'telefone' => '(11) 5051-2737',
                'endereco' => 'Av. Macuco, 494',
                'bairro' => 'Moema',
                'cidade' => 'São Paulo',
                'site' => 'http://www.labufalinadoc.com.br',
                'cep' => '04523-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            119 => 
            array (
                'id' => 126,
                'nome' => 'Lá de Minas',
            'telefone' => '(11) 5535-4805',
                'endereco' => 'Rua Califórnia, 1.170',
                'bairro' => 'Brooklin',
                'cidade' => 'São Paulo',
                'site' => 'http://lademinas.com.br',
                'cep' => '04566-062',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            120 => 
            array (
                'id' => 127,
                'nome' => 'La Pastina',
            'telefone' => '(11) 3383-7477 / (11) 3085-3055',
                'endereco' => 'Rua Padre João Manuel, 1269',
                'bairro' => 'Jardim Paulista',
                'cidade' => 'São Paulo',
                'site' => 'http://www.worldwine.com.br',
                'cep' => '01411-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            121 => 
            array (
                'id' => 128,
                'nome' => 'La Reggiana',
            'telefone' => '(11) 5095-9900 / (11) 5095-5099 / (11) 5543-2099',
                'endereco' => 'Av Morumbi 8567',
                'bairro' => 'Santo Amaro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.lareggiana.com.br',
                'cep' => '04703-004',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            122 => 
            array (
                'id' => 129,
                'nome' => 'Laticínios D\'Oro',
            'telefone' => '(11) 3032-3536 / (11) 3812-0562',
                'endereco' => 'R. Pedro Cristi, 31-71 - Mercado de Pinheiros, Boxes 06/07',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            123 => 
            array (
                'id' => 130,
                'nome' => 'Laticínios Maria Eugênia / Queijos Roni',
            'telefone' => '(11) 3228-2097 / (11) 3228-3099',
                'endereco' => 'Rua da Cantareira, 306 - Mercado Municipal de São Paulo, Box 2',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://correiogourmand.com.br/guias_gourmands_06_mercadao_sao_paulo_03_boxes_laticinios.htm',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            124 => 
            array (
                'id' => 131,
                'nome' => 'Lebanon Market Center',
            'telefone' => '(11) 5052-9849 / (11) 5052-8475',
                'endereco' => 'Al. dos Nhambiquaras, 374',
                'bairro' => 'Indianópolis',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '04090-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            125 => 
            array (
                'id' => 132,
                'nome' => 'Lewis Ferraz e José Domingos',
            'telefone' => '(11) 3731-5961 / (11) 9265-7999',
            'endereco' => 'Feira da Vila Madalena na Rua Mourato Coelho (entre as ruas Fradique Coutinho e Wizard)',
                'bairro' => 'Vila Madalena',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            126 => 
            array (
                'id' => 133,
                'nome' => 'Lousada & Lousada',
            'telefone' => '(11) 3812-1792',
                'endereco' => 'R. Pedro Cristi, 89 - Mercado de Pinheiros, Boxes 31',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            127 => 
            array (
                'id' => 134,
                'nome' => 'Mario Santoni',
            'telefone' => '(11) 3283-0442',
                'endereco' => 'Rua Joaquim Eugênio de Lima, 209',
                'bairro' => 'Bela Vista',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01403-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            128 => 
            array (
                'id' => 135,
                'nome' => 'Meeta Ravindra',
            'telefone' => '(11) 4339-2134 / (11) 4339-1859',
                'endereco' => '',
                'bairro' => '',
                'cidade' => '',
                'site' => '',
                'cep' => '',
                'estado' => '',
                'pais' => '',
            ),
            129 => 
            array (
                'id' => 136,
                'nome' => 'Casa Zilanna',
            'telefone' => '(11) 3257-8671',
                'endereco' => 'Rua Itambé, 506',
                'bairro' => 'Consolação',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01239-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            130 => 
            array (
                'id' => 137,
                'nome' => 'Mercado Municipal da Lapa',
            'telefone' => '(11) 3832-1834',
                'endereco' => 'Rua Herbart, 47',
                'bairro' => 'Lapa',
                'cidade' => 'São Paulo',
                'site' => 'http://mercadodalapa.blogspot.com',
                'cep' => '05072-030',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            131 => 
            array (
                'id' => 138,
                'nome' => 'Mercado Municipal Central',
            'telefone' => '(11) 3228-0673',
                'endereco' => 'Rua da Cantareira, 306',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.mercadomunicipal.com.br',
                'cep' => '01024-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            132 => 
            array (
                'id' => 139,
                'nome' => 'Mercado Municipal de Pinheiros',
            'telefone' => '(11) 3032-3551 / (11) 3518-9096',
                'endereco' => 'Rua Pedro Cristi, 89',
                'bairro' => 'Pinheiros',
                'cidade' => 'São Paulo',
                'site' => 'http://www.prefeitura.sp.gov.br',
                'cep' => '05421-040',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            133 => 
            array (
                'id' => 140,
                'nome' => 'Mercado Municipal de Santo Amaro',
            'telefone' => '(11) 5687-2707',
                'endereco' => 'Rua Min. Roberto Cardoso Alves, 359',
                'bairro' => 'Santo Amaro',
                'cidade' => 'São Paulo',
                'site' => 'http://www.prefeitura.sp.gov.br',
                'cep' => '04737-000',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            134 => 
            array (
                'id' => 141,
                'nome' => 'Mercado Municipal Kinjo Yamato',
            'telefone' => '(11) 3228-0339',
                'endereco' => 'Rua da Cantareira, 377',
                'bairro' => 'Sé',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01024-100',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            135 => 
            array (
                'id' => 142,
            'nome' => 'Comércio de Pescado Pacífico (Mestiço)',
            'telefone' => '(11) 3256-2082 / (11) 3256-2399',
                'endereco' => 'R. Fernando de Albuquerque, 288',
                'bairro' => 'Consolação',
                'cidade' => 'São Paulo',
                'site' => '',
                'cep' => '01309-030',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
            136 => 
            array (
                'id' => 143,
                'nome' => 'Avental e Cia',
            'telefone' => '(11)3227-5034 / (11) 3227-8621',
                'endereco' => 'Rua Paula Souza, 123',
                'bairro' => 'Santa Efigênia',
                'cidade' => 'São Paulo',
                'site' => 'www.aventalecia.com',
                'cep' => '01027-001',
                'estado' => 'São Paulo',
                'pais' => 'Brasil',
            ),
        ));
        
        
    }
}